### ISSUE TITLE
HTML escaper breaks URLs as Unicode isolation characters are escaped

### ISSUE THREAD

**Issue by codeinthehole** [django-ftl/django-ftl#6]
* django-ftl version: v0.13

### The problem

In v0.13, the `html_escaper` namespace specifies `use_isolating=True`:
https://github.com/django-ftl/django-ftl/blob/v0.13/src/django_ftl/bundles.py#L132-L140

This means HTML messages that contain anchors such as:
```
link-msg-html = this is <a href="{ $url }">link</a>
```
are incorrectly translated as the Unicode isolation characters are escaped as `%E2%81%A8` and %E2%81%A9`, changing the URL. 

In practice, users will complain about getting 404s when clicking on links.

### Proposed solution

I think this should be changed to `use_isolating=False`. 

This is the recommendation in the fluent-compiler docs:
https://fluent-compiler.readthedocs.io/en/latest/escaping.html#example

![image](https://user-images.githubusercontent.com/80975/219360268-fe7b5ff9-5d59-4745-9819-15e955b81963.png)

Happy to submit a PR with this fix if you agree.

**Comment by spookylukey** [comment]
So, I actually wrote those docs in fluent-compiler, but forgot to obey them in django-ftl! A PR would be gratefully received.

**Comment by codeinthehole** [comment]
Could do with some guidance on what the right fix is.

Setting `use_isolating=False` in the `html_escaper` namespace doesn't seem to change the escaping behaviour. 

It doesn't look like the Fluent compiler uses the `use_isolating` attribute of any passed in escapers. It's not referenced anywhere in the `RegisteredEscaper` class that wraps the `escaper` object:
https://github.com/django-ftl/fluent-compiler/blob/v0.2/src/fluent_compiler/escapers.py#L57-L124

Only the value of the `use_isolating` param passed to the `fluent_compiler.compile_messages` function seems to be used.

So, I'm not quite sure what form the fix should take. Should we extend the `RegisteredEscaper` class to wrap the `use_isolating` attribute? And what should be the relationship between the value of `use_isolating` passed to `compiled_messages` and the attribute in the escaper?

No rush to reply - we can work around this in the project that uses this package. And thanks for creating and maintaining it.

**Comment by spookylukey** [comment]
Wow, it looks like I simply forgot to implement that feature! It's about 4 years ago now, so I can't remember what happened. I'll have a look into it.

I think the simplest workaround for now is to pass `use_isolating=False` to the Bundle constructor, although that may have downsides.

**Comment by spookylukey** [comment]
New version released, 0.14, with the fix, along with a new version of fluent_compiler which needed the documented feature actually adding. Please re-open if there are any problems.

**Comment by spookylukey** [comment]
@codeinthehole as a matter of curiosity, can I ask what is the project you are involved in that uses django-ftl? No worries if that's private, or you could reply by email if you want.
